# Generated by Django 2.2.3 on 2019-09-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_music', '0002_auto_20190925_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user_id',
        ),
    ]
